apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kata-containers
  - psa-restricted
  - envoy-gateway
  - spegel
  - weave-gitops
  - headlamp
  - runner-autoscaler
  - cloudflared
