apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: weave-gitops
      version: "4.0.36"
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
  values:
    adminUser:
      create: true
      createSecret: true
      username: "admin"
      passwordHash: "$2a$12$JEdioLbAPM0rC7YsaKzKxOgiqUN/NxAeriaJyHA7VVpQPLOWyGQ9q"
    rbac:
      create: true
      impersonationResourceNames: ["admin"]
