apiVersion: v1
kind: Service
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  selector:
    gateway.envoyproxy.io/owning-gateway-name: eg
  ports:
    - name: http
      port: 80
      targetPort: 8080
