name: version-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Version
        uses: Greewil/version-update-helper@gha/validate-version/v1
        with:
          check-git-diff: false
